ALTER TABLE images DROP CONSTRAINT IF EXISTS fk_image_hotel;
ALTER TABLE images DROP CONSTRAINT IF EXISTS fk_image_room;

ALTER TABLE images ADD CONSTRAINT fk_image_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
ALTER TABLE images ADD CONSTRAINT fk_image_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE;