name: CI/CD with Github Actions

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Setup Java JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'corretto'
                  cache: maven
            - name: Build application jar
              working-directory: ./
              run: mvn clean install
            - name: Build Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                dockerfile: Dockerfile
                build-args: |
                  SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
                  DATABASE_URL=${{ secrets.DATABASE_URL }}
                push: false
                tags: |
                    ${{ secrets.DOCKER_HUB_USERNAME }}/booking-app-backend:latest
                    ${{ secrets.DOCKER_HUB_USERNAME }}/booking-app-backend:${{ github.run_id }}
            - name: push images to Docker Hub
              run: |
                docker image push ${{ secrets.DOCKER_HUB_USERNAME }}/booking-app-backend:latest
                docker image push ${{ secrets.DOCKER_HUB_USERNAME }}/booking-app-backend:${{ github.run_id }}
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Update app image on VM
              run: |
                cd /root
                sudo docker compose pull booking-app-backend
                sudo docker compose rm -fs booking-app-backend
                sudo docker compose up -d booking-app-backend


           
              